-- MySQL Script generated by MySQL Workbench
-- Thu Oct 14 10:28:27 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb`;
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`modelo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`modelo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`modelo` (
  `id_modelo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `precio` DOUBLE NOT NULL,
  `activo` TINYINT DEFAULT 1 NOT NULL,
  PRIMARY KEY (`id_modelo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`linea_de_montaje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`linea_de_montaje` ;

CREATE TABLE IF NOT EXISTS `mydb`.`linea_de_montaje` (
  `id_linea_de_montaje` INT NOT NULL AUTO_INCREMENT,
  `id_modelo` INT NOT NULL,
  `id_primer_estacion` INT NULL,
  `activo` TINYINT DEFAULT 1 NOT NULL,
  PRIMARY KEY (`id_linea_de_montaje`),
  INDEX `fk_lineaDeMontaje_modelo1_idx` (`id_modelo` ASC) VISIBLE,
  INDEX `fk_lineaDeMontaje_estacion1_idx` (`id_primer_estacion` ASC) VISIBLE,
  CONSTRAINT `fk_lineaDeMontaje_modelo1`
    FOREIGN KEY (`id_modelo`)
    REFERENCES `mydb`.`modelo` (`id_modelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lineaDeMontaje_estacion1`
    FOREIGN KEY (`id_primer_estacion`)
    REFERENCES `mydb`.`estacion` (`id_estacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`estacion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`estacion` (
  `id_estacion` INT NOT NULL AUTO_INCREMENT,
  `tarea` VARCHAR(45) NOT NULL,
  `id_linea_de_montaje` INT NOT NULL,
  `id_estacion_siguiente` INT NULL,
    `activo` TINYINT DEFAULT 1 NOT NULL,
  PRIMARY KEY (`id_estacion`, `id_linea_de_montaje`),
  INDEX `fk_estacion_lineaDeMontaje1_idx` (`id_linea_de_montaje` ASC) VISIBLE,
  CONSTRAINT `fk_estacion_lineaDeMontaje1`
    FOREIGN KEY (`id_linea_de_montaje`)
    REFERENCES `mydb`.`linea_de_montaje` (`id_linea_de_montaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`concesionaria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`concesionaria` ;

CREATE TABLE IF NOT EXISTS `mydb`.`concesionaria` (
  `id_concesionaria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
    `activo` TINYINT DEFAULT 1 NOT NULL,
  PRIMARY KEY (`id_concesionaria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`venta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`venta` ;

CREATE TABLE IF NOT EXISTS `mydb`.`venta` (
  `id_venta` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `cuit` VARCHAR(45) NOT NULL,
  `id_concesionaria` INT NOT NULL,
    `activo` TINYINT DEFAULT 1 NOT NULL,
  PRIMARY KEY (`id_venta`),
  INDEX `fk_venta_concesionaria1_idx` (`id_concesionaria` ASC) VISIBLE,
  CONSTRAINT `fk_venta_concesionaria1`
    FOREIGN KEY (`id_concesionaria`)
    REFERENCES `mydb`.`concesionaria` (`id_concesionaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detalle_venta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`detalle_venta` ;

CREATE TABLE IF NOT EXISTS `mydb`.`detalle_venta` (
  `id_modelo` INT NOT NULL,
  `id_venta` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio_unitario` DOUBLE NOT NULL,
  `precio_final` DOUBLE NOT NULL,
    `activo` TINYINT DEFAULT 1 NOT NULL,
  PRIMARY KEY (`id_modelo`, `id_venta`),
  INDEX `fk_modelo_has_venta_venta1_idx` (`id_venta` ASC) VISIBLE,
  INDEX `fk_modelo_has_venta_modelo1_idx` (`id_modelo` ASC) VISIBLE,
  CONSTRAINT `fk_modelo_has_venta_modelo1`
    FOREIGN KEY (`id_modelo`)
    REFERENCES `mydb`.`modelo` (`id_modelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_modelo_has_venta_venta1`
    FOREIGN KEY (`id_venta`)
    REFERENCES `mydb`.`venta` (`id_venta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vehiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`vehiculo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`vehiculo` (
  `num_chasis` VARCHAR(45) NOT NULL,
  `fecha_de_inicio` DATE NOT NULL,
  `fecha_de_fin` DATE DEFAULT NULL,
  `id_modelo` INT NOT NULL,
  `id_venta` INT NOT NULL,
  `patente` VARCHAR(10) NOT NULL,
    `activo` TINYINT DEFAULT 1 NOT NULL,
  PRIMARY KEY (`num_chasis`),
  INDEX `fk_vehiculo_detalleVenta1_idx` (`id_modelo` ASC, `id_venta` ASC) VISIBLE,
  CONSTRAINT `fk_vehiculo_detalleVenta1`
    FOREIGN KEY (`id_modelo` , `id_venta`)
    REFERENCES `mydb`.`detalle_venta` (`id_modelo` , `id_venta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estacion_vehiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`estacion_vehiculo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`estacion_vehiculo` (
  `id_estacion` INT NOT NULL,
  `num_chasis` VARCHAR(45) NOT NULL,
  `fecha_de_ingreso` DATE NOT NULL,
  `fecha_salida` DATE NULL,
    `activo` TINYINT DEFAULT 1 NOT NULL,
  PRIMARY KEY (`id_estacion`, `num_chasis`),
  INDEX `fk_estacion_has_vehiculo_vehiculo1_idx` (`num_chasis` ASC) VISIBLE,
  INDEX `fk_estacion_has_vehiculo_estacion_idx` (`id_estacion` ASC) VISIBLE,
  CONSTRAINT `fk_estacion_has_vehiculo_estacion`
    FOREIGN KEY (`id_estacion`)
    REFERENCES `mydb`.`estacion` (`id_estacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estacion_has_vehiculo_vehiculo1`
    FOREIGN KEY (`num_chasis`)
    REFERENCES `mydb`.`vehiculo` (`num_chasis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`insumo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`insumo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`insumo` (
  `id_insumo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
    `activo` TINYINT DEFAULT 1 NOT NULL,
  PRIMARY KEY (`id_insumo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`insumo_estacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`insumo_estacion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`insumo_estacion` (
  `id_insumo` INT NOT NULL,
  `id_estacion` INT NOT NULL,
  `id_linea_de_montaje` INT NOT NULL,
  `cantidad` DOUBLE NOT NULL,
    `activo` TINYINT DEFAULT 1 NOT NULL,
  INDEX `fk_insumo_has_estacion_estacion1_idx` (`id_estacion` ASC, `id_linea_de_montaje` ASC) VISIBLE,
  INDEX `fk_insumo_has_estacion_insumo1_idx` (`id_insumo` ASC) VISIBLE,
  PRIMARY KEY (`id_insumo`, `id_estacion`, `id_linea_de_montaje`),
  CONSTRAINT `fk_insumo_has_estacion_insumo1`
    FOREIGN KEY (`id_insumo`)
    REFERENCES `mydb`.`insumo` (`id_insumo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_insumo_has_estacion_estacion1`
    FOREIGN KEY (`id_estacion` , `id_linea_de_montaje`)
    REFERENCES `mydb`.`estacion` (`id_estacion` , `id_linea_de_montaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`proveedor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`proveedor` (
  `id_proveedor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
    `activo` TINYINT DEFAULT 1 NOT NULL,
  PRIMARY KEY (`id_proveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proveedor_insumo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`proveedor_insumo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`proveedor_insumo` (
  `id_proveedor` INT NOT NULL,
  `id_insumo` INT NOT NULL,
  `precio_actual` FLOAT NOT NULL,
    `activo` TINYINT DEFAULT 1 NOT NULL,
  PRIMARY KEY (`id_proveedor`, `id_insumo`),
  INDEX `fk_proveedor_has_insumo_insumo1_idx` (`id_insumo` ASC) VISIBLE,
  INDEX `fk_proveedor_has_insumo_proveedor1_idx` (`id_proveedor` ASC) VISIBLE,
  CONSTRAINT `fk_proveedor_has_insumo_proveedor1`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `mydb`.`proveedor` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proveedor_has_insumo_insumo1`
    FOREIGN KEY (`id_insumo`)
    REFERENCES `mydb`.`insumo` (`id_insumo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedido_insumo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pedido_insumo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pedido_insumo` (
  `id_pedido_insumo` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `precio` DOUBLE NOT NULL,
  `cantidad` INT NOT NULL,
  `id_insumo` INT NOT NULL,
    `activo` TINYINT DEFAULT 1 NOT NULL,
  PRIMARY KEY (`id_pedido_insumo`),
  INDEX `fk_pedidoInsumo_insumo1_idx` (`id_insumo` ASC) VISIBLE,
  CONSTRAINT `fk_pedidoInsumo_insumo1`
    FOREIGN KEY (`id_insumo`)
    REFERENCES `mydb`.`insumo` (`id_insumo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
