-- MySQL Script generated by MySQL Workbench
-- Wed Sep 29 18:49:53 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bd1` ;

-- -----------------------------------------------------
-- Schema bd1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd1` DEFAULT CHARACTER SET utf8 ;
USE `bd1` ;

-- -----------------------------------------------------
-- Table `bd1`.`modelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd1`.`modelo` (
  `id_modelo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `precio` DOUBLE NOT NULL,
  `activo` TINYINT NOT NULL,
  PRIMARY KEY (`id_modelo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd1`.`linea_de_montaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd1`.`linea_de_montaje` (
  `id_linea_de_montaje` INT NOT NULL,
  `id_modelo` INT NOT NULL,
  `id_primer_estacion` INT NULL,
  PRIMARY KEY (`id_linea_de_montaje`),
  CONSTRAINT `fk_lineaDeMontaje_modelo1`
    FOREIGN KEY (`id_modelo`)
    REFERENCES `bd1`.`modelo` (`id_modelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lineaDeMontaje_estacion1`
    FOREIGN KEY (`id_primer_estacion`)
    REFERENCES `bd1`.`estacion` (`id_estacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_lineaDeMontaje_modelo1_idx` ON `bd1`.`linea_de_montaje` (`id_modelo` ASC) VISIBLE;

CREATE INDEX `fk_lineaDeMontaje_estacion1_idx` ON `bd1`.`linea_de_montaje` (`id_primer_estacion` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bd1`.`estacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd1`.`estacion` (
  `id_estacion` INT NOT NULL AUTO_INCREMENT,
  `tarea` VARCHAR(45) NOT NULL,
  `id_linea_de_montaje` INT NOT NULL,
  `id_estacion_siguiente` INT NULL,
  `activo` TINYINT NOT NULL,
  PRIMARY KEY (`id_estacion`, `id_linea_de_montaje`),
  CONSTRAINT `fk_estacion_lineaDeMontaje1`
    FOREIGN KEY (`id_linea_de_montaje`)
    REFERENCES `bd1`.`linea_de_montaje` (`id_linea_de_montaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estacion_estacion1`
    FOREIGN KEY (`id_estacion_siguiente`)
    REFERENCES `bd1`.`estacion` (`id_estacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_estacion_lineaDeMontaje1_idx` ON `bd1`.`estacion` (`id_linea_de_montaje` ASC) VISIBLE;

CREATE INDEX `fk_estacion_estacion1_idx` ON `bd1`.`estacion` (`id_estacion_siguiente` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bd1`.`concesionaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd1`.`concesionaria` (
  `id_consesionaria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `activo` TINYINT NOT NULL,
  PRIMARY KEY (`id_consesionaria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd1`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd1`.`venta` (
  `id_venta` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `cuit` VARCHAR(45) NOT NULL,
  `id_consesionaria` INT NOT NULL,
  `activo` TINYINT NOT NULL,
  PRIMARY KEY (`id_venta`),
  CONSTRAINT `fk_venta_consesionaria1`
    FOREIGN KEY (`id_consesionaria`)
    REFERENCES `bd1`.`concesionaria` (`id_consesionaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_venta_consesionaria1_idx` ON `bd1`.`venta` (`id_consesionaria` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bd1`.`detalle_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd1`.`detalle_venta` (
  `id_modelo` INT NOT NULL,
  `id_venta` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio_unitario` DOUBLE NOT NULL,
  `precio_final` DOUBLE NOT NULL,
  `activo` TINYINT NOT NULL,
  PRIMARY KEY (`id_modelo`, `id_venta`),
  CONSTRAINT `fk_modelo_has_venta_modelo1`
    FOREIGN KEY (`id_modelo`)
    REFERENCES `bd1`.`modelo` (`id_modelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_modelo_has_venta_venta1`
    FOREIGN KEY (`id_venta`)
    REFERENCES `bd1`.`venta` (`id_venta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_modelo_has_venta_venta1_idx` ON `bd1`.`detalle_venta` (`id_venta` ASC) VISIBLE;

CREATE INDEX `fk_modelo_has_venta_modelo1_idx` ON `bd1`.`detalle_venta` (`id_modelo` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bd1`.`vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd1`.`vehiculo` (
  `num_chasis` VARCHAR(45) NOT NULL,
  `fecha_de_inicio` DATE NOT NULL,
  `fecha_de_fin` DATE NOT NULL,
  `id_modelo` INT NOT NULL,
  `id_venta` INT NOT NULL,
  `activo` TINYINT NOT NULL,
  PRIMARY KEY (`num_chasis`),
  CONSTRAINT `fk_vehiculo_detalleVenta1`
    FOREIGN KEY (`id_modelo` , `id_venta`)
    REFERENCES `bd1`.`detalle_venta` (`id_modelo` , `id_venta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_vehiculo_detalleVenta1_idx` ON `bd1`.`vehiculo` (`id_modelo` ASC, `id_venta` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bd1`.`estacion_vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd1`.`estacion_vehiculo` (
  `id_estacion` INT NOT NULL,
  `num_chasis` VARCHAR(45) NOT NULL,
  `fecha_de_ingreso` DATE NOT NULL,
  `fecha_salida` DATE NOT NULL,
  PRIMARY KEY (`id_estacion`, `num_chasis`),
  CONSTRAINT `fk_estacion_has_vehiculo_estacion`
    FOREIGN KEY (`id_estacion`)
    REFERENCES `bd1`.`estacion` (`id_estacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estacion_has_vehiculo_vehiculo1`
    FOREIGN KEY (`num_chasis`)
    REFERENCES `bd1`.`vehiculo` (`num_chasis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_estacion_has_vehiculo_vehiculo1_idx` ON `bd1`.`estacion_vehiculo` (`num_chasis` ASC) VISIBLE;

CREATE INDEX `fk_estacion_has_vehiculo_estacion_idx` ON `bd1`.`estacion_vehiculo` (`id_estacion` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bd1`.`insumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd1`.`insumo` (
  `id_insumo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `activo` TINYINT NOT NULL,
  PRIMARY KEY (`id_insumo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd1`.`insumo_estacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd1`.`insumo_estacion` (
  `id_insumo` INT NOT NULL,
  `id_estacion` INT NOT NULL,
  `id_linea_de_montaje` INT NOT NULL,
  `cantidad` DOUBLE NOT NULL,
  PRIMARY KEY (`id_insumo`, `id_estacion`, `id_linea_de_montaje`),
  CONSTRAINT `fk_insumo_has_estacion_insumo1`
    FOREIGN KEY (`id_insumo`)
    REFERENCES `bd1`.`insumo` (`id_insumo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_insumo_has_estacion_estacion1`
    FOREIGN KEY (`id_estacion` , `id_linea_de_montaje`)
    REFERENCES `bd1`.`estacion` (`id_estacion` , `id_linea_de_montaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_insumo_has_estacion_estacion1_idx` ON `bd1`.`insumo_estacion` (`id_estacion` ASC, `id_linea_de_montaje` ASC) VISIBLE;

CREATE INDEX `fk_insumo_has_estacion_insumo1_idx` ON `bd1`.`insumo_estacion` (`id_insumo` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bd1`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd1`.`proveedor` (
  `id_proveedor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `activo` TINYINT NOT NULL,
  PRIMARY KEY (`id_proveedor`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `nombre_UNIQUE` ON `bd1`.`proveedor` (`nombre` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bd1`.`proveedor_insumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd1`.`proveedor_insumo` (
  `id_proveedor` INT NOT NULL,
  `id_insumo` INT NOT NULL,
  `precio_actual` FLOAT NOT NULL,
  `activo` TINYINT NOT NULL,
  PRIMARY KEY (`id_proveedor`, `id_insumo`),
  CONSTRAINT `fk_proveedor_has_insumo_proveedor1`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `bd1`.`proveedor` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proveedor_has_insumo_insumo1`
    FOREIGN KEY (`id_insumo`)
    REFERENCES `bd1`.`insumo` (`id_insumo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_proveedor_has_insumo_insumo1_idx` ON `bd1`.`proveedor_insumo` (`id_insumo` ASC) VISIBLE;

CREATE INDEX `fk_proveedor_has_insumo_proveedor1_idx` ON `bd1`.`proveedor_insumo` (`id_proveedor` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bd1`.`pedido_insumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd1`.`pedido_insumo` (
  `id_pedido_insumo` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `precio` DOUBLE NOT NULL,
  `cantidad` INT NOT NULL,
  `id_insumo` INT NOT NULL,
  `activo` TINYINT NOT NULL,
  PRIMARY KEY (`id_pedido_insumo`),
  CONSTRAINT `fk_pedidoInsumo_insumo1`
    FOREIGN KEY (`id_insumo`)
    REFERENCES `bd1`.`insumo` (`id_insumo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_pedidoInsumo_insumo1_idx` ON `bd1`.`pedido_insumo` (`id_insumo` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

